127.0.0.1/earist/certificate_of_registration/		http://localhost/phpmyadmin/index.php?route=/sql&pos=0&db=earist&table=certificate_of_registration

   Showing rows 0 - 11 (12 total, Query took 0.0004 seconds.)


SELECT * FROM `certificate_of_registration`


registration_no	academic_year_term	student_no	name	gender	age	email_address	college	program	major	year_level	curriculum	scholarship_discount	subject_code	subject_title	lec_units	lab_units	credit_units	tuition_units	subject_section	subject_schedule_room	subject_faculty	total_lec_units	total_lab_units	total_credit_units	total_tuition	tuition	athletic_fee	cultural_fee	development_fee	guidance_fee	library_fee	medical_dental_fee	registration_fee	computer_fee	laboratory_fee	total_assessment	less_financial_aid	net_assessed	credit_memo	total_discount	total_payment	outstanding_balance	first_payment_due	second_payment_due	third_payment_due	payment_validation_date	official_receipt	
2147483647	Second Semester AY 2024-2025	234-03193M	GARCIA, SEAN LATRELL	MALE	20	seanlatrellgarcia@gmail.com	College of Computing Studies	Bachelor of Science in Information Technology	NULL	Second Year-Regular	2018-2019	UNIFAST-FHE	DBMSLAB2	Database Management System 2 (Laboratory)	0	1	1	1	BSINFOTECH2C	TH 06:00PM-09:00PM	Carlos, Ernanie	14	5	20	20	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483649	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	DBMSLEC2	Database Management System 2 (Lecture)	2	0	2	2	BSINFOTECH2C	T 11:00AM-01:00PM	Carlos, Ernanie
	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483650	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	GEELECCP	Communicative Proficiency in Business Corresponden...	3	0	3	3	BSINFOTECH2C	TH 07:00AM-10:00AM	Pardito, Ranilo	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483652	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	GEPEHEF2	Physical Activity Towards Health and Fitness II	2	0	2	2	BSINFOTECH2C	W 07:00AM-10:00AM	Barizo Jr., Crisanto 
	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483654	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	INTHCILB	Introduction to Human Computer Interaction (Labora...	0	0	1	1	BSINFOTECH2C	W 10:00PM-01:00PM	Macasil, Ma. Jasmine
Rose	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483655	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	INTHCILC	Introduction to Human Computer Interaction (Lectur...	2	0	2	2	BSINFOTECH2C	T 01:00PM-03:00PM	Macasil, Ma. Jasmine
Rose	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483657	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	IPATLAB1	Integrative Programming and Technologies 1 (Labora...	0	2	2	2	BSINFOTECH2C	TH 11:00 AM-02:00PM	San Jose, Dhani	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483658	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	IPATLEC1	Integrative Programming and Technologies 1 (Lectur...	1	0	1	1	BSINFOTECH2C	T 08:00AM-10:00AM	San Jose, Dhani	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483659	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NETWKLB1	Networking 1 (Laboratory)	0	1	1	1	BSINFOTECH2C	T 03:00PM-06:00PM	Almazan, Edmund	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483660	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NETWKLC1	Networking 1 (Lecture)	2	0	2	2	BSINFOTECH2C	TH 03:00PM-05:00PM	Almazan, Edmund	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483661	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	WEBDVLB2	Web Development 2 (Laboratory)	0	1	1	1	BSINFOTECH2C	W 01:00PM-04:00PM	Sison, Edgardo	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
2147483662	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	WEBDVLC2	Web Development 2 (Lecture)	2	0	2	2	BSINFOTECH2C	T 10:00AM-01:00PM	Sison, Edgardo	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	NULL	
